apiVersion: v1
kind: ConfigMap
metadata:
  name: health-check-service-config
data:
  # KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_BOOTSTRAP_PRODUCERS: "kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.default.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.default.svc.cluster.local:9092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-health-check-service-config
data:
  # KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_BOOTSTRAP_CONSUMERS: "kafka.default.svc.cluster.local:9092"
  KAFKA_GROUP_ID: "health_check_group"
