apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-check-service
  template:
    metadata:
      labels:
        app: health-check-service
    spec:
      containers:
        - name: health-check-service
          image: local-registry/health-check-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: health-check-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: health-check-service
spec:
  selector:
    app: health-check-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: health-check-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-check-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50